/* eslint-disable no-sparse-arrays */
import {
  Work1,
  Work2,
  Work3,
  Work4,
  Work5,
  Work6,
  Work7,
  Work8,
  Work9,
  Work10,
  Work11,
  Work12,
  Work13,
  Work14,
  Work15,
  Work16,
  Work17,
  Work18,
  Work19,
  Work20,
  Work21,
  Work22,
  Work23,
  Work24,
  Work25,
  Work26,
} from "./Image";

const Menu = [
  {
    id: 1,
    image: Work1,
    title: "Chezz Food",
    category: "Web",
    link: "https://chezzfood.netlify.app",
    github_link: "https://github.com/Freedom-seven/Cheese-food",
  },
  {
    id: 2,
    image: Work2,
    title: "Brownies Hotel",
    category: "Web",
    link: "https://browny.netlify.app",
    github_link: "https://github.com/Freedom-seven/Browny-hotel",
  },
  {
    id: 3,
    image: Work3,
    title: "BeeTech",
    category: "Web",
    link: "https://beetechblog.netlify.app",
    github_link: "https://github.com/Freedom-seven/bee-tech",
  },
  ,
  {
    id: 4,
    image: Work4,
    title: "Elite Homes",
    category: "Web",
    link: "https://elitehome.netlify.app",
    github_link: "https://github.com/Freedom-seven/Elite-homes",
  },
  ,
  {
    id: 5,
    image: Work5,
    title: "Flower Boutique",
    category: "Web",
    link: "https://flowerboutique.netlify.app",
    github_link: "https://github.com/Freedom-seven/Flower-boutique",
  },

  ,
  {
    id: 6,
    image: Work6,
    title: "Tulip Restaurant",
    category: "Web",
    link: "https://tuliprestaurant.netlify.app",
    github_link: "https://github.com/Freedom-seven/Tulip-restaurant",
  },
  ,
  {
    id: 7,
    image: Work7,
    title: "The Fitness Club",
    category: "Web",
    link: "https://thefitnessclub.netlify.app",
    github_link: "https://github.com/Freedom-seven/theFitClub",
  },
  ,
  {
    id: 8,
    image: Work8,
    title: "Oganic Foods",
    category: "Web",
    link: "https://oganicfoods.netlify.app",
    github_link: "https://github.com/Freedom-seven/Grocery-Store",
  },
  ,
  {
    id: 9,
    image: Work9,
    title: "Trip Hub",
    category: "Web",
    link: "https://triphub.netlify.app",
    github_link: "https://github.com/Freedom-seven/Trip-hub",
  },
  ,
  {
    id: 10,
    image: Work10,
    title: "Covid-19 Tracker",
    category: "Web",
    link: "https://covvid19tracker.netlify.app",
    github_link: "https://github.com/Freedom-seven/covid-19-tracker",
  },
  ,
  {
    id: 11,
    image: Work11,
    title: "Netflix Clone",
    category: "Web",
    link: "https://realnetflixclone.netlify.app",
    github_link: "https://github.com/Freedom-seven/netflix-clone",
  },
  ,
  {
    id: 12,
    image: Work12,
    title: "Resort Hotel",
    category: "Web",
    link: "https://hotelbeachresorts.netlify.app",
    github_link: "https://github.com/Freedom-seven/resort",
  },
  ,
  {
    id: 13,
    image: Work13,
    title: "Tesla Clone",
    category: "Web",
    link: "https://elated-tesla-clone.netlify.app",
    github_link: "https://github.com/Freedom-seven/tesla-clone",
  },
  ,
  {
    id: 14,
    image: Work14,
    title: "Amazon Clone",
    category: "Web",
    link: "https://comfy-amazon.netlify.app",
    github_link: "https://github.com/Freedom-seven/amazon-clone",
  },
  ,
  {
    id: 15,
    image: Work15,
    title: "Krypto Trade",
    category: "Web",
    link: "https://kryptotrade.netlify.app",
    github_link: "https://github.com/Freedom-seven/web3.0",
  },
  ,
  {
    id: 16,
    image: Work16,
    title: "Timeless Tour",
    category: "Web",
    link: "https://timelesstour.netlify.app",
    github_link: "https://github.com/Freedom-seven/Africa",
  },
  ,
  {
    id: 17,
    image: Work17,
    title: "Purpl Pay",
    category: "Mobile",
    github_link: "https://github.com/Freedom-seven/Purpl_Pay",
  },
  ,
  {
    id: 18,
    image: Work18,
    title: "Toggle Buttons",
    category: "Design",
    link: "https://delightful-tarsier-fd7d23.netlify.app",
    github_link: "https://github.com/Freedom-seven/Toggle-btn",
  },
  ,
  {
    id: 19,
    image: Work19,
    title: "Balance",
    category: "Design",
    link: "https://adorable-entremet-593eee.netlify.app",
    github_link: "https://github.com/Freedom-seven/Balance-animation",
  },
  ,
  {
    id: 20,
    image: Work20,
    title: "Bouncing Cycles",
    category: "Design",
    link: "https://taupe-cat-3e4912.netlify.app",
    github_link: "https://github.com/Freedom-seven/Bouncing-cycles",
  },
  ,
  {
    id: 21,
    image: Work21,
    title: "Creadit Card",
    category: "Design",
    link: "https://frabjous-elf-b7341e.netlify.app",
    github_link: "https://github.com/Freedom-seven/Credit-card",
  },
  ,
  {
    id: 22,
    image: Work22,
    title: "Glow Animation",
    category: "Design",
    link: "https://scintillating-cassata-912915.netlify.app",
    github_link: "https://github.com/Freedom-seven/Glow",
  },
  ,
  {
    id: 23,
    image: Work23,
    title: "Hot Cup of Tea",
    category: "Design",
    link: "https://courageous-genie-c58060.netlify.app",
    github_link: "https://github.com/Freedom-seven/Hot-cup-of-tea",
  },
  ,
  {
    id: 24,
    image: Work24,
    title: "Lamp Animation",
    category: "Design",
    link: "https://dulcet-manatee-cfcb45.netlify.app",
    github_link: "https://github.com/Freedom-seven/Lamp-animation",
  },
  {
    id: 25,
    image: Work25,
    title: "Product Card",
    category: "Design",
    link: "https://jade-otter-30f570.netlify.app",
    github_link: "https://github.com/Freedom-seven/Product-card",
  },
  {
    id: 26,
    image: Work26,
    title: "Flying Plane",
    category: "Design",
    link: "https://dainty-platypus-3bd868.netlify.app",
    github_link: "https://github.com/Freedom-seven/Plane",
  },
];

export default Menu;
