const Data = [
  {
    id: 1,
    category: "education",
    icon: "icon-graduation",
    // year: "2021 - 2022",
    title: "CodeTrain",
    desc: "Gained hands-on experience in software development through the program at CodeTrain, with a focus on modern technologies and frameworks. Strengthened skills in software development, including HTML, CSS, JavaScript, and frameworks such as React, React Native, MongoDB, ExpressJs, and Node.js. Developed an understanding of secure and scalable systems, as well as the ability to work in a collaborative environment. Worked on various personal and team projects, showcasing the skills acquired in a practical setting.",
  },
  // {
  //   id: 2,
  //   category: "education",
  //   icon: "icon-graduation",
  //   year: "2013 - 2017",
  //   title: "Bachelor's Degree",
  //   desc: "Lorem ipsum dolor sit amet quo ei simul congue exerci     ad nec admodum perfecto.",
  // },
  // {
  //   id: 3,
  //   category: "education",
  //   icon: "icon-graduation",
  //   year: "2009 - 2013",
  //   title: "Honours Degree",
  //   desc: "Lorem ipsum dolor sit amet quo ei simul congue exerci     ad nec admodum perfecto.",
  // },
  {
    id: 2,
    category: "experience",
    icon: "icon-briefcase",
    // year: "2022",
    title: "Purpl Pay",
    desc: "As the lead developer, I worked on a mobile payment app that allowed users to securely and easily make payments using their mobile devices. I was responsible for designing and implementing the app's user interface, integrating it with payment gateways, and ensuring that the app met security and compliance requirements. Key technologies used in this project include React Native, Node.js, and Stripe API.",
  },
  {
    id: 3,
    category: "experience",
    icon: "icon-briefcase",
    // year: "2022",
    title: "KrytoTrade",
    desc: "I collaborated with a team of designers and developers to build a decentralized trading platform on the blockchain using Web 3.0 technologies. I was responsible for developing the smart contract that facilitated trades and integrating it with the platform's frontend. Key technologies used in this project include Solidity, React, and Ethereum blockchain.",
  },
  {
    id: 4,
    category: "experience",
    icon: "icon-briefcase",
    // year: "2021",
    title: "COVID-19 Tracker",
    desc: "I created a web-based tool that tracked the spread of COVID-19 in real-time. I used APIs from reliable sources to gather and display data about cases, deaths, and recoveries, and implemented a user-friendly interface that made it easy for users to access the information they needed. Key technologies used in this project include React, JavaScript, and Chart.js.",
  },
  {
    id: 5,
    category: "experience",
    icon: "icon-briefcase",
    // year: "2022",
    title: "Oganic Foods",
    desc: "I developed an e-commerce website for a local organic food store that allowed users to order products online and have them delivered to their doorstep. I designed the website's user interface, implemented the shopping cart and checkout systems, and integrated it with a payment gateway. Key technologies used in this project include HTML, CSS, JavaScript, and WooCommerce.",
  },
  {
    id: 6,
    category: "experience",
    icon: "icon-briefcase",
    // year: "2022",
    title: "Tulip Restaurant",
    desc: "I built a website for a small restaurant that showcased its menu. I designed the website's user interface, and ensured that it was responsive and accessible on all devices. Key technologies used in this project include HTML, CSS, and JavaScript.",
  },
  // {
  //   id: 6,
  //   category: "experience",
  //   icon: "icon-briefcase",
  //   year: "2009 - 2013",
  //   title: "Back-End Developer",
  //   desc: "Lorem ipsum dolor sit amet quo ei simul congue exerci     ad nec admodum perfecto.",
  // },
];

export default Data;
